config/routes.rb
Rails.application.routes.draw do
 
  
  post '/cart/add/:product_id/update' => 'cart#update_quantity', as:"cart_quantity_update"
  delete '/cart/destroy/:product_id'  => 'cart#destroy', as: 'line_item_deleted'

  post '/cart/add/:product_id' =>'cart#add_item', as:"cart_add_item"
  get '/cart/index' =>'cart#index'
  post '/cart/index' =>'cart#index'
  root 'home#home'
  get '/about' => 'home#about'
  get '/flavours' => 'home#index'
  get '/flavours/:id' => 'home#show', as:'flavour'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/' => 'home#destroy'


  # post '/signup' => 'user#create'
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy, :index]
  resources :orders

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :product, optional: true 
    belongs_to :cart,  optional: true
    belongs_to :user, optional: true
    belongs_to :order, optional: true
    def total_price 
        self.product.price * quantity
    end 
end

app/models/product.rb
class Product < ApplicationRecord
    has_and_belongs_to_many :specials
    has_many :line_items
end

app/models/special.rb
class Special < ApplicationRecord
    has_and_belongs_to_many :products
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
    has_many :line_items
    has_many :orders
end      
               

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  def fetch_user
    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
    end
    session[:user_id] = nil unless @current_user.present?
  end  # fetch_user()
  
def check_if_logged_in 
    unless @current_user.present?
      flash[:error] = 'Please Log in'
      redirect_to login_path
    end # login check
  end  # check_if_logged_in()
end  # class ApplicationController

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :check_if_logged_in

  def add_item
    @item=LineItem.create product_id: params[:product_id], quantity: 1, user_id: @current_user.id 
    redirect_to flavours_path 
  end

  def update_quantity
    @item = LineItem.find_by(product_id: params[:product_id])
    @item.update quantity: params[:quantity]
    redirect_to cart_index_path
  end

  def destroy
    @item = LineItem.find_by(product_id: params[:product_id])
    @item.destroy
    redirect_to cart_index_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    fetch_user
  end

  def index
    @products = Product.all
  end

  def show 
    @product = Product.find params[:id]
  end

  def destroy
    session[:user_id] = nil 
    redirect_to root_path 
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user =User.find_by email: params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id 
      redirect_to root_path
    else 
      flash[:error]="Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
    redirect_to login_path unless session[:user_id] == @current_user.id
  end

  def update  
    user = User.find params[:id]
    user.update user_params
    redirect_to user_path(params[:id])
  end

  def destroy
    User.destroy params[:id]
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :password, :email, :address, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/cart/index.html.erb
<h2>Shopping Cart</h2>
<ul>
  <% @current_user.line_items.order(:created_at).each do |i| %>
      <li class="cart-list">
        <strong>  Name:</strong><%= i.product.name %> <br>
        <strong>  Quantity: </strong><%= i.quantity %> <br>
        <strong> Total Price: </strong><%= i.total_price %> <br>
        <br>
        <%= form_with url: cart_quantity_update_path(i.product.id), local: true do |f| %>
        <strong>Change Quantity:</strong>
        <%= f.text_field :quantity, value: i.quantity%>
        <br>
        <%= f.submit 'Update' %> 
        <%end%>
        <%= button_to 'Delete', line_item_deleted_path(i.product.id), method:'delete' %>
      </li>
  <% end %>
</ul>
<%= link_to '<button type="button", class="cart-button checkout-button">Check Out</button>'.html_safe, root_path, method: "get" %>

app/views/home/_header.html.erb
<nav id="navbar" class="">
  <div class="nav-wrapper">
    <div class="logo">
    <%= link_to "/" do %>
    <%= image_tag("logo.png", :class => "nav-logo") %>
    <% end %>
    </div>

    <ul id="menu">
      <li> <%= link_to "HOME", root_path %> </li>
      <li> <%= link_to "FLAVOURS", flavours_path %> </li>
      <li> <%= link_to "SHOP", flavours_path %> </li>
      <li> <%= link_to "ABOUT US", about_path %> </li>     
      <% if @current_user.present?%>
          Welcome, <%= @current_user.first_name %>
          |
          <li> <%= link_to 'Edit Info', edit_user_path(@current_user) %></li>
          |
          <li> <%= link_to 'Show Info', user_path(@current_user.id)%> </li>
          | 
          <li> <%= link_to 'Logout', root_path, method: 'delete' %></li>

          <%= link_to image_tag("cart.png", :class=>"cart-logo"), cart_index_path,  alt:"cart logo" %> 
      <% else %>  
          <li>  <%= link_to 'Login', login_path %></li>
          |
          <li> <%= link_to 'Sign up', new_user_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<header class='masthead'>
  <p class='masthead-intro'>Hi We are</p>
  <h1 class='masthead-heading'>ACE ICE CREAM!</h1>
</header>
<section class="introduction-section">
    <h1>Introduction</h1>
    <p>Ace Ice Cream is a new Australian ice cream shop, focused on serving texture-driven handcrafted ice creams with a renewed attention to flavor and palate. We develop each recipe specifically for each individual flavor. The integrity of our ingredients is never compromised with additives or processed stabilizing. We look to change the way people eat and think about this nostalgic treat, by giving ice cream lovers an entirely original and contemporary ice cream experience.</p>
</section>
<section class="questions-section">
    <h1>FAQS</h1>
    <h2>What are your popular flavours?</h2>
    <p>Our popular flavours are <strong>Peachy Oolong</strong>, <strong>Uji Matcha</strong>, <strong>Mango Pomelo</strong> and <strong>Taro</strong>!</p>
    <h2>Do you use artificial flavouring?</h2>
    <p>No, all of our ice cream is artificial flavouring free. You can taste the difference.</p>
    <h2>Do you have sugar free ice cream?</h2>
    <p>No, sorry. All our gelato and sorbet contain sugar. There’s no beating round the bush. Treat yo self, really means treat yourself</p>
    <h2>Do you franchise?</h2>
    <p>No, we do not franchise. We are entirely privately owned and run.</p>
</section>
<footer class="section-footer">
      <div class="container">
        <div>
          <h2>Ace Ice Cream</h2>
          <a href="https://www.instagram.com/ace.icecreamm/">
          <img src="https://www.edigitalagency.com.au/wp-content/uploads/instagram-logo-svg-vector-for-print.svg" alt="" class="insta" />
            <i class="fab fa-instagram fa-2x"></i>
          </a>
          <a href="https://www.facebook.com/aceicecreamsydney">
          <img src="https://www.designbust.com/download/640/png/facebook_logo_transparent512.png" alt="" class="facebook" />
            <i class="fab fa-facebook fa-2x"></i>
          </a>
        </div>
        <div>
          <h3>Company Info</h3>
          <ul>
            <li><a href="#">All Products</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Delivery Info</a></li>
          </ul>
        </div>
        <div>
          <h3>Company Value</h3>
          <ul>
            <li><a href="#">No Artificial Flavour</a></li>
            <li><a href="#">No Artificial Colouring</a></li>
            <li><a href="#">Small Batch Making</a></li>
            <li><a href="#">Only Use Fresh Milk&Cream</a></li>
          </ul>
        </div>
      </div>
    </footer>

app/views/home/home.html.erb
<section id="home" class="section-showcase">
  <div class="container">
    <div>
      <h1>Hand crafted Ice Cream</h1>
      <p>
        Ace Ice Cream is a new Australian ice cream shop, focused on serving texture-driven handcrafted ice creams with a renewed attention to flavour and palate.
      </p>
        <%= link_to "Explore", flavours_path, class: "btn"%> 
    </div>
    <img src="https://i.pinimg.com/564x/ef/17/2f/ef172f8432dfbf0b58c946bb3e5e1c2c.jpg" alt="" />
  </div>
</section>

<section id="about" class="section-large-text">
  <div class="overlay">
    <div class="section-large-text-inner">
      <h3>Our Place</h3>
      <h2>We Just ❤️ Ice Cream</h2>
      <p>
        Ace Ice Cream is a new Australian ice cream shop, focused on serving texture-driven handcrafted ice creams with a renewed attention to flavor and palate. We develop each recipe specifically for each individual flavor. The integrity of our ingredients is never compromised with additives or processed stabilizing. We look to change the way people eat and think about this nostalgic treat, by giving ice cream lovers an entirely original and contemporary ice cream experience.
      </p>
    </div>
  </div>
</section>

<section class="section-gallery">
  <div class="gallery">
    <img src="https://i.pinimg.com/564x/20/6f/62/206f62569c6d1d88718345b1913d9fc2.jpg" alt="" class="big" />
    <img src="https://i.pinimg.com/564x/ed/b9/fc/edb9fc080f5fb0b67e2a04cce83ef7f1.jpg" alt="" class="big" />
    <img src="https://i.pinimg.com/564x/37/be/6b/37be6bfeeda860dd65bf1d7736e3e40a.jpg" alt="" class="big" />
    <img src="https://i.pinimg.com/564x/8e/29/60/8e29600041eac3ffd9e53ffade7eacaf.jpg" alt="" class="big" />
    <img src="https://i.pinimg.com/564x/c4/f4/d5/c4f4d530f5862a9f2f25daa7159d7f54.jpg" alt="" class="big" />
    <img src="https://i.pinimg.com/564x/8e/87/bd/8e87bd81576b0d5a54674fea6aab5077.jpg" alt="" class="big" />
  </div>
</section>

<footer class="section-footer">
  <div class="container">
    <div>
      <h2>Ace Ice Cream</h2>
      <a href="https://www.instagram.com/ace.icecreamm/">
      <img src="https://www.edigitalagency.com.au/wp-content/uploads/instagram-logo-svg-vector-for-print.svg" alt="" class="insta" />
        <i class="fab fa-instagram fa-2x"></i>
      </a>
      <a href="https://www.facebook.com/aceicecreamsydney">
      <img src="https://www.designbust.com/download/640/png/facebook_logo_transparent512.png" alt="" class="facebook" />
        <i class="fab fa-facebook fa-2x"></i>
      </a>
    </div>
    <div>
      <h3>Company Info</h3>
      <ul>
        <li><a href="#">All Products</a></li>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Delivery Info</a></li>
      </ul>
    </div>
    <div>
      <h3>Company Value</h3>
      <ul>
        <li><a href="#">No Artificial Flavour</a></li>
        <li><a href="#">No Artificial Colouring</a></li>
        <li><a href="#">Small Batch Making</a></li>
        <li><a href="#">Only Use Fresh Milk&Cream</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/home/index.html.erb
<h2> ICE CREAM FLAVOURS </h2>
<div id="gallery">
   <ul id="grid">
      <% @products.each do |product| %>
         <li> <%= link_to image_tag(product.image), flavour_path(product.id), class:"icecream-photo", alt:product.name %> </li>
      <% end %>
   </ul>
</div>

app/views/home/show.html.erb
<h2 class="description">Flavour: <%= @product.name %></h2>
<div class="show-icecream">
    <p>
        <strong>Description:</strong>
        <%= @product.description %>
    </p>
    <p>
        <strong>Price:</strong>
        $<%= @product.price %>
    </p>
    <p>
        <strong>Stock:</strong>
        <%= @product.stock %>
    </p>
        <%= image_tag @product.image, class:"icecream-photo", alt:@product.name %>
        <%= link_to '<button type="button", class="cart-button">Add to Cart</button>'.html_safe, cart_add_item_path(@product.id), method: "post" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "application/favicon" %>
    <title>Aceicecream</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class='yield'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/session/new.html.erb
<h2 id="login-text">Login</h2>
<% if flash[:error] %>
    <br>
    <strong id="error">
        <%= flash[:error] %>
    </strong>
    <br>
    <br>
<% end %>

<%= form_with url:login_path, local: true do |f|%>
    <%= f.label :email %>
    <br>
    <%= f.text_field :email %>
    <br><br>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
    <br><br>
    <%= f.submit 'Login' %>
<% end%>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f|%>
<%= f.label :first_name %>
<br>
<%= f.text_field :first_name %>
<br><br>
<%= f.label :last_name %>
<br>
<%= f.text_field :last_name %>
<br><br>
<%= f.label :email %>
<br>
<%= f.text_field :email %>
<br><br>
<%= f.label :phone %>
<br>
<%= f.text_field :phone  %>
<br><br>
<%= f.label :address %>
<br>
<%= f.text_field :address %>
<br><br>
<%= f.label :password %>
<br>
<%= f.password_field :password %>
<br><br>

<%= f.submit "Confirm" %>

</label>

<%end%>

app/views/users/edit.html.erb
<h2>Update Info</h2>
<%= render partial: 'form' %>
  

app/views/users/index.html.erb
<h2>Edit Your Info</h2>
<ul>
  <% @users.each do |u| %>
  <li>
    <%= link_to u.first_name, user_path(u.id)%>
    <% if @current_user.present? && session[:user_id] == @current_user.id %>
      (<%= link_to 'edit', edit_user_path(u.id) %>)
    <%end%>
  </li>
  <%end%>
</ul>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<%= render partial: 'form' %>

app/views/users/show.html.erb
<p><strong>First name:</strong>
  <%= @user.first_name%>
</p>
<p><strong>Last name:</strong>
  <%= @user.last_name%>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong> 
  <%= @user.phone %>
</p>

<p>
  <strong>Address:</strong> 
  <%= @user.address %>
</p>